#!/bin/sh -f

#set -x

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

. ../mgr/build_header

if [ ${build_visual} = "yes" ] ; then
  libs="${libs} user32.lib"
fi

. ../mgr/build_generic

if [ ${build_app} = "yes" ] ; then

  if [ ${build_visual} = "yes" ] ; then
    cppflags="${cppflags} /I."
    cppflags="${cppflags} /wd4305 /wd4244"
  else
    cppflags="${cppflags} -I."
  fi

  libs="${build_path}/lib${libname}.a ${libs}"

  objs=
  app_src=./test.cxx
  app_exe=test
  . ${inlib_mgr}/build_app

fi
